services:
  mysql-dev:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: resart
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: resart
    ports:
      - 3306:3306
