name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
          node-version: 18
    - run: npm install -g yarn cypress ts-node prisma
    - run: yarn install --frozen-lockfile
    - run: yarn docker-compose
    - run: cp .env.dev .env
    - run: prisma db migrate dev
    - run: prisma db seed
    - run: yarn build
    - run: yarn start
    - run: cypress run
