name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses:
            name: Prettier Check
            uses:
                docker://ghcr.io/peaceiris/actions-prettier@v3
            with:
                prettier_options: --check

  cypress-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: resart
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: resart
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
          node-version: 18
    - run: npm install -g yarn cypress ts-node prisma pm2
    - run: yarn install --frozen-lockfile
    - run: cp .env.dev .env
    - run: prisma migrate dev
    - run: prisma db seed
    - run: yarn build
    - run: sudo npx pm2 start
    - run: yarn cypress:ci
