name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
    - name: Run cypress tests
      with:
        node-version: 12
    - run: npm install -g yarn cypress
    - run: yarn install --frozen-lockfile
    - run: yarn docker-compose
    - run: yarn build
    - run: yarn start
    - run: cypress run
